package moe.crx.roadblock.objects.game

enum class CarCustomizationLockableSection {
    Customization,
    Paintjobs,
    DualTone,
    Calipers,
    Rims,
    CarbonParts,
    NeonTubes,
    MaterialMetallic,
    MaterialMatte,
    MaterialMetallicRims,
    MaterialMatteRims,
    Decals,
    Tires,
    BodyParts,
    BodyPartsRoof,
    BodyPartsWing,
    BodyPartsSkirts,
    BodyPartsSpoilerFront,
    BodyPartsSpoilerRear,
    TintedGlass,
    LicensePlate,
    BodyPartsHood,
    BodyPartsTrunk,
}