package moe.crx.roadblock.objects.game

enum class MissionType {
    Stunts,
    BarrelRolls,
    FlatSpins,
    DriftMeters,
    Airtime,
    PerfectNitro,
    PerfectRun,
    Shockwave,
    DriveDistance,
    Destructibles,
    Knockdown,
    TrafficKnockdown,
    VerticalKnockdown,
    SandwichKnockdown,
    ShockwaveKnockdown,
    FlatSpinKnockdown,
    FinishedRaces,
    WinRaces,
    ReputationLevel,
    CareerFlags,
    CompleteSeasons,
    CarsOwned,
    GarageLevel,
    CarsWithUnlockedTiers,
    LevelsUpgraded,
    UpgradeItemsApplied,
    PlayedTLEs,
    WinTLECredits,
    WinCareerEvents,
    WinCareerRacingCredits,
    MultiplayerRaces,
    MultiplayerCredits,
}